### ISSUE TITLE
About equation（6）

### ISSUE THREAD

**Issue by malajikuai** [enoche/ImRec#1]
![image](https://user-images.githubusercontent.com/52128451/183022412-ecea53cf-2c9a-44f9-837b-2798998cd9c7.png)
So, in the code, I didn't find the "small postive infinitesimal quantity", it seems like you just use the similarity vector,right？

**Comment by enoche** [comment]
Hi, malajikuai, thanks for your interest on this repo.

> it seems like you just use the similarity vector,right？
Yes. 
The adding of $\epsilon$ theoretically ensures the representation are not zero.
In implementation, the similarity vector hardly ever results in a zero vector, so I omit it in the code.

**Comment by malajikuai** [comment]
Ok, I see,thanks.
