### ISSUE TITLE
Little questions

### ISSUE THREAD

**Issue by malajikuai** [enoche/ImRec#2]
![image](https://user-images.githubusercontent.com/52128451/183089881-3b5c89f1-2af8-4a8d-aa7e-f4f8d5735f1d.png)

Hello,
  I noted the introduction has such a sentences, "The authors of LightGCN place learnable weights to dynamically integrate information from both the ego layer and all hidden layers but find no improvement [3].",how to understand the weights?ps: the above equation is the propagation rules in NGCF.

**Comment by enoche** [comment]
Hi, malajikuai, 

Nice point.
Here I mentioned "learnable weights", I mean the weights $\alpha$ on layers are learnable in Equation (8) of LightGCN paper.
Weights $\alpha$ are parameterized on hidden layers as well as the ego layer in Equation (8) of LightGCN.
You may also would like to check Section 3.3 in LightGCN paper to understand the statement.
Do let me know if my comments could ease your concern.

ps. Following is the Equation (8) of LightGCN.
<img width="557" alt="image" src="https://user-images.githubusercontent.com/5653236/183101134-7a6d4a63-46e5-4ab0-91a1-bc5a24f63bb9.png">

**Comment by malajikuai** [comment]
Thanks for your help.
But i still have a question about the layer refinement mechanism's description," Nevertheless, in our propagation stage, we extract the information from the ego layer dynamically by designing a layer refinement mechanism".In here, the model firstly get (l+1)-th representation,then calculates similarity between  current layer and the ego layer, finally according to the similartity obtains (l+1)-th outputs.How to understand extract the information from the ego layer?

**Comment by enoche** [comment]
> How to understand extract the information from the ego layer?

As your have mentioned, LayerGCN first get (l+1)-th representation with normal GCN propagation and aggregation, it then refines the obtained representation by weighing it with the similarity between (l+1)-th and the ego layer. You may think the similarity function as an attention mechanism that refines information of (l+1)-th layer from the ego layer.

**Comment by enoche** [comment]
Just found a blog posted from others: https://zhuanlan.zhihu.com/p/546791001. This may help @malajikuai .
