### ISSUE TITLE
mooc datasets

### ISSUE THREAD

**Issue by malajikuai** [enoche/ImRec#3]
Hello, I download the mooc dataset from http://moocdata.cn, but the dataset differs from ml-100k because it does not have timestamp and there is bug during data processing, how can I solve this problem?

**Comment by enoche** [comment]
Thanks for posting your issue. 
Great! You are getting your hands dirty on the code and datasets. The original MOOC datasets we used for recommendation follows : https://github.com/jerryhao66/HRL

moocdata.cn holds the detailed logs of MOOC dataset.
