### ISSUE TITLE
 integrate model

### ISSUE THREAD

**Issue by ademvincent** [enoche/ImRec#4]
Hello，can you integrate this model:NGAT4Rec: Neighbor-Aware Graph Attention Network For Recommendation?
address：https://github.com/ShortVideoRecommendation/NGAT4Rec.git
The performance of this model is better than  lightgcn. I want to have a look at the comparison with layergcn.

**Comment by enoche** [comment]
Hi, thanks for posting.
I've checked NGAT4Rec model in this file: https://github.com/ShortVideoRecommendation/NGAT4Rec/blob/master/DGLModels/SubgraphModels/NGAT.py
The model is built on DGL, and it may not straightforward for integration. I'll try it and report to you then. 
BTW, do you know this model published any where under peer-review?

**Comment by ademvincent** [comment]
Thank you very much for answering my question, but I'm sorry I don't know this either.

**Comment by enoche** [comment]
> Thank you very much for answering my question, but I'm sorry I don't know this either.

OK, in this case, I would recommend to integrate models or select your baselines that has passed the peer-review. That is, the model/paper has accepted or published under conferences or journals. 
`Neighbor-Aware Graph Attention Network ` is not new concept. I would encourage you find other published paper related to this concept. Thanks.

**Comment by ademvincent** [comment]
Got it. Thank you.

**Comment by enoche** [comment]
> Got it. Thank you.

Once you have found a published/accepted model with source code (pytorch/tensorflow), I am glad to integrate it.

**Comment by ademvincent** [comment]
> > Got it. Thank you.
> 
> Once you have found a published/accepted model with source code (pytorch/tensorflow), I am glad to integrate it.

Ok, I'm reading a WWW'22 paper "STAM: A Spatiotemporal Aggregation Method for Graph Neural Network-based Recommendation" recently. 
In the experimental part of the paper, the performance of this model on MovieLens data set is more than 20% higher than lightgcn.
It's implemented by Tensorflow. Can you integrate this model? 
Address: https://github.com/zyang-16/STAM.git

**Comment by ademvincent** [comment]
> > Got it. Thank you.
> 
> Once you have found a published/accepted model with source code (pytorch/tensorflow), I am glad to integrate it.

Ok, I'm reading a WWW'22 paper "STAM: A Spatiotemporal Aggregation Method for Graph Neural Network-based Recommendation" recently. 
In the experimental part of the paper, the performance of this model on MovieLens data set is more than 20% higher than lightgcn.
It's implemented by Tensorflow. Can you integrate this model? 
Address: https://github.com/zyang-16/STAM.git

**Comment by enoche** [comment]
> > > Got it. Thank you.
> > 
> > 
> > Once you have found a published/accepted model with source code (pytorch/tensorflow), I am glad to integrate it.
> 
> Ok, I'm reading a WWW'22 paper "STAM: A Spatiotemporal Aggregation Method for Graph Neural Network-based Recommendation" recently. In the experimental part of the paper, the performance of this model on MovieLens data set is more than 20% higher than lightgcn. It's implemented by Tensorflow. Can you integrate this model? Address: https://github.com/zyang-16/STAM.git

Nice to read the paper. I found the paper targets on Sequential Recommendation, you may refer recbole for this topic: https://github.com/RUCAIBox/RecBole

Sorry to say that this repo. focus on General Recommendation.

**Comment by ademvincent** [comment]
> > > > Got it. Thank you.
> > > 
> > > 
> > > Once you have found a published/accepted model with source code (pytorch/tensorflow), I am glad to integrate it.
> > 
> > 
> > Ok, I'm reading a WWW'22 paper "STAM: A Spatiotemporal Aggregation Method for Graph Neural Network-based Recommendation" recently. In the experimental part of the paper, the performance of this model on MovieLens data set is more than 20% higher than lightgcn. It's implemented by Tensorflow. Can you integrate this model? Address: https://github.com/zyang-16/STAM.git
> 
> Nice to read the paper. I found the paper targets on Sequential Recommendation, you may refer recbole for this topic: https://github.com/RUCAIBox/RecBole
> 
> Sorry to say that this repo. focus on General Recommendation.

I see, thank you for your answer.
