### ISSUE TITLE
关于EHCF复现的问题

### ISSUE THREAD

**Issue by Acsltw** [enoche/ImRec#5]
作者您好！我个人使用pytorch和TensorFlow对原作者的模型进行复现，TensorFlow复现的结果基本一致，但是pytorch复现的结果很不理想，loss在下降但是recall和ndcg反复波动，不存在一个明显的提升趋势。我看了您对EHCF模型的复现，但是有点没看明白逻辑，所以我想下有单独包含EHCF的复现文件吗，类似原作者一个模型的所有代码都包含在一个py文件里的？

**Comment by enoche** [comment]
谢谢关注！
> 所以我想下有单独包含EHCF的复现文件吗，类似原作者一个模型的所有代码都包含在一个py文件里的？
现在所有代码都是pytorch的，你可以自己组织成为一个文件。

另外，你可以在configs里面设置EHCF的参数，由于原paper中没有调整参数空间的设置，所以需要自己设置~

你那边方便详细说明参数的设置、数据集的设置，及你跑的结果。

**Comment by Acsltw** [comment]
非常荣幸能够这么快的得到您的回复！我将具体的问题以邮件的形式发到了您的邮箱！希望能够得到进一步的交流
