### ISSUE TITLE
LayerGCN复现的一些问题

### ISSUE THREAD

**Issue by tan90du** [enoche/ImRec#6]
你好，我在mooc数据集复现LayerGCN（full）时，MOOC | 0.1 | 1e-03，跑出来的实验结果并不能和论文报告的一致，甚至差很多，下面是实验结果：
Mon 01 Apr 2024 23:17:50 INFO 	Parameters: ['seed', 'n_layers', 'dropout', 'reg_weight']=(999, 4, 0.1, 0.001),
Valid: recall@10: 0.2759    recall@20: 0.4031    recall@50: 0.5679    ndcg@10: 0.1694    ndcg@20: 0.2047    ndcg@50: 0.2417    ,
Test: recall@10: 0.2511    recall@20: 0.3736    recall@50: 0.5431    ndcg@10: 0.1680    ndcg@20: 0.2050    ndcg@50: 0.2469    
但是我在LayerGCN（w/o Dropout)） MOOC | 0.0 | 1e-02，能够复现论文报告的结果，下面是实验结果：
Tue 02 Apr 2024 09:10:11 INFO 	Parameters: ['seed', 'n_layers', 'dropout', 'reg_weight']=(999, 4, 0.0, 0.01),
Valid: recall@10: 0.2740    recall@20: 0.3971    recall@50: 0.5643    ndcg@10: 0.1683    ndcg@20: 0.2027    ndcg@50: 0.2400    ,
Test: recall@10: 0.2615    recall@20: 0.3890    recall@50: 0.5419    ndcg@10: 0.1754    ndcg@20: 0.2154    ndcg@50: 0.2526    

我看到论文说LayerGCN（full）使用了5个随机种子，可能是这个原因，可否将论文中LayerGCN（full）使用的随机种子提供一下，方便复现。或许我有其他的一些细节没有注意到。期待您的解答，谢谢！

**Comment by enoche** [comment]
@tan90du  谢谢您的反馈！ 这个是我当时跑的结果：

> Tue 05 Apr 2022 17:03:39 INFO   Parameters: ['seed', 'n_layers', 'dropout', 'reg_weight']=(999, 4, 0.1, 0.001),
> Valid: recall@5: 0.1835    recall@10: 0.2930    recall@20: 0.4059    recall@50: 0.5795    ndcg@5: 0.1367    ndcg@10: 0.1748    ndcg@20: 0.2067    ndcg@50: 0.2455    map@5: 0.1079    map@10: 0.1243    map@20: 0.1336    map@50: 0.1407    precision@5: 0.0598    precision@10: 0.0467    precision@20: 0.0326    precision@50: 0.0188    ,
> Test: recall@5: 0.1779    recall@10: 0.2801    recall@20: 0.3979    recall@50: 0.5572    ndcg@5: 0.1514    ndcg@10: 0.1909    ndcg@20: 0.2272    ndcg@50: 0.2665    map@5: 0.1219    map@10: 0.1434    map@20: 0.1539    map@50: 0.1618    precision@5: 0.0976    precision@10: 0.0733    precision@20: 0.0509    precision@50: 0.0280 

关于随机种子，我是用了999附近的几个，我找不到当时的log文件了，您那边选几个试试看。

**Comment by enoche** [comment]
另外不同的硬件、软件环境也有一定的影响，建议您那边grid search一下最优参数。
