### ISSUE TITLE
 A._update(data_dict) 会报错，这行代码是做什么用的？

### ISSUE THREAD

**Issue by Yhfish9** [enoche/ImRec#9]
每个 模型里的A._update(data_dict)都有问题，删除后，LayerGCN每次跑的结果都一样Trainable parameters: 4702016
06 Nov 13:49    INFO epoch 0 training [time: 149.10s, train loss: 222504.9066]
06 Nov 13:49    INFO epoch 0 evaluating [time: 4.82s, valid_score: 0.199500]
06 Nov 13:49    INFO valid result: 
recall@5: 0.0305    recall@10: 0.0918    recall@20: 0.1995    recall@50: 0.2737    ndcg@5: 0.0250    ndcg@10: 0.0461    ndcg@20: 0.0764    ndcg@50: 0.0930    map@5: 0.0213    map@10: 0.0288    map@20: 0.0369    map@50: 0.0397    precision@5: 0.0085    precision@10: 0.0139    precision@20: 0.0157    precision@50: 0.0087    
06 Nov 13:49    INFO test result: 
recall@5: 0.0357    recall@10: 0.0772    recall@20: 0.1664    recall@50: 0.2260    ndcg@5: 0.0331    ndcg@10: 0.0482    ndcg@20: 0.0748    ndcg@50: 0.0890    map@5: 0.0266    map@10: 0.0316    map@20: 0.0384    map@50: 0.0407    precision@5: 0.0133    precision@10: 0.0152    precision@20: 0.0169    precision@50: 0.0095    
06 Nov 13:49    INFO ██Saving current best: saved\LayerGCN-Nov-06-2024-13-47-04.pth
06 Nov 13:51    INFO epoch 1 training [time: 127.65s, train loss: 222441.7419]
06 Nov 13:52    INFO epoch 1 evaluating [time: 5.41s, valid_score: 0.199500]
06 Nov 13:52    INFO valid result: 
recall@5: 0.0305    recall@10: 0.0918    recall@20: 0.1995    recall@50: 0.2737    ndcg@5: 0.0250    ndcg@10: 0.0461    ndcg@20: 0.0764    ndcg@50: 0.0930    map@5: 0.0213    map@10: 0.0288    map@20: 0.0369    map@50: 0.0397    precision@5: 0.0085    precision@10: 0.0139    precision@20: 0.0157    precision@50: 0.0087    
06 Nov 13:52    INFO test result: 
recall@5: 0.0357    recall@10: 0.0772    recall@20: 0.1664    recall@50: 0.2260    ndcg@5: 0.0331    ndcg@10: 0.0482    ndcg@20: 0.0748    ndcg@50: 0.0890    map@5: 0.0266    map@10: 0.0316    map@20: 0.0384    map@50: 0.0407    precision@5: 0.0133    precision@10: 0.0152    precision@20: 0.0169    precision@50: 0.0095

**Comment by enoche** [comment]
Hi 谢谢反馈，方便提供 不删除时，详细的报错信息吗？

**Comment by Yhfish9** [comment]
你好。没想到能这么快就收到回复了，下面是报错信息：line 100, in get_norm_adj_mat
    A._update(data_dict)
AttributeError: 'dok_matrix' object has no attribute '_update'

**Comment by Yhfish9** [comment]
你好。没想到能这么快就收到回复了，下面是报错信息：line 100, in get_norm_adj_mat
    A._update(data_dict)
AttributeError: 'dok_matrix' object has no attribute '_update'

**Comment by enoche** [comment]
嗯，可能现在换成  A.update了。你可以试试~

参考这边：https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.dok_matrix.update.html#scipy.sparse.dok_matrix.update

**Comment by Yhfish9** [comment]
我用的是python3.9 和scipy 1.13.1，如果换成A.update会出另外一个错误 
File "D:\develop\anaconda3\envs\py3_9\lib\site-packages\scipy\sparse\_dok.py", line 62, in update
    raise NotImplementedError("Direct update to DOK sparse format is not allowed.")
NotImplementedError: Direct update to DOK sparse format is not allowed.

**Comment by Yhfish9** [comment]
通过降低scipy的版本到1.7.1成功解决了
